apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubernetes.io/change-cause: kubectl deployment.apps/freebail-frontend set image
      deployment.v1.apps/freebail-frontend simple-nginx=gcr.io/freebail-wedding/simple-nginx:0.1.0
      --record=true
  creationTimestamp: 2019-08-04T10:18:07Z
  generation: 5
  labels:
    app: freebail-frontend
  name: freebail-frontend
  namespace: default
  resourceVersion: "368429"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/freebail-frontend
  uid: 2743ba9e-b6a1-11e9-b296-42010a9a01fd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: freebail-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: freebail-frontend
    spec:
      containers:
      - image: gcr.io/GOOGLE_CLOUD_PROJECT/freebail-frontend:COMMIT_SHA
        name: simple-nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-08-04T10:18:07Z
    lastUpdateTime: 2019-08-05T22:10:47Z
    message: ReplicaSet "freebail-frontend-6d5bbb6f68" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2019-08-05T22:25:05Z
    lastUpdateTime: 2019-08-05T22:25:05Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
